repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: stable
    hooks:
      - id: black
        language_version: python3.10  # Specify your Python version

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--strict]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.2
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Add more hooks for formatting or linting if necessary

  # Django test hook (example)
  - repo: https://github.com/pre-commit/mirrors-django
    rev: v3.2.8
    hooks:
      - id: django-test-check
